//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogiCore.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int Order_id { get; set; }
        public int Manager_id { get; set; }
        public int Cargo_id { get; set; }
        public int Tariff_id { get; set; }
        public int Truck_id { get; set; }
        public int Route_id { get; set; }
        public string Status_order { get; set; }
        public Nullable<System.DateTime> Order_date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> Scheduled_pickup { get; set; }
        public Nullable<System.DateTime> Scheduled_delivery { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Route Route { get; set; }
        public virtual Tariff Tariff { get; set; }
        public virtual Truck Truck { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
