//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogiCore.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_id { get; set; }
        public int Order_id { get; set; }
        public decimal Amount { get; set; }
        public string Status_payment { get; set; }
        public Nullable<System.DateTime> Transaction_date { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
